# Generated by Django 5.0.7 on 2024-08-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostainvestimento',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
