# Generated by Django 5.0.7 on 2024-08-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0002_propostainvestimento_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propostainvestimento',
            name='data',
        ),
    ]
